-- AGE-839: deterministic ordering for review_events.
--
-- `created_at` (timestamptz) can tie when two events land in the same clock
-- tick (pglite ms resolution in tests; µs on Neon), and `id` is a random UUID,
-- so "latest event" reads were nondeterministic at ties. `seq` is a monotonic
-- insertion counter used as a tie-breaker: ORDER BY created_at DESC, seq DESC.
-- Existing rows are backfilled in arbitrary order, which is acceptable — only
-- same-timestamp ties among NEW rows carry ordering semantics.

ALTER TABLE review_events
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;
